language: ruby
rvm:
  - 2.4.0
  - 2.3.3
before_install:
  # Workaround for https://github.com/sickill/rainbow/issues/48
  - gem update --system
  - gem install bundler -v 1.13.7
script:
  - bundle exec rubocop
  - bundle exec rspec
